if(NOT DEFINED DRAKON_ROOT)
  message(FATAL_ERROR "DRAKON_ROOT is required")
endif()

set(DRAKON_INFERENCE_DIR "${DRAKON_ROOT}/data/inference/cam_test_01/2026/05/21/23")
set(DRAKON_INFERENCE_PATH "${DRAKON_INFERENCE_DIR}/inf_fixture_alert_01.json")
set(DRAKON_INFERENCE_INDEX "${DRAKON_ROOT}/data/indexes/inference.jsonl")

file(MAKE_DIRECTORY "${DRAKON_INFERENCE_DIR}")
file(MAKE_DIRECTORY "${DRAKON_ROOT}/data/indexes")

file(WRITE "${DRAKON_INFERENCE_PATH}" [=[
{
  "schema_version": "drakon.inference.v1",
  "inference_id": "inf_fixture_alert_01",
  "frame_id": "frame_fixture_alert_01",
  "camera_id": "cam_test_01",
  "timestamp": "2026-05-21T23:00:00.000Z",
  "timestamp_utc": "2026-05-21T23:00:00.000Z",
  "frame_timestamp_utc": "2026-05-21T23:00:00.000Z",
  "job_id": "job_fixture_alert",
  "model_provider": "mock",
  "model": "mock-frame-analyzer-v1",
  "prompt": {
    "prompt_id": "fixture_alert",
    "prompt_version": "v1",
    "template": "fixture"
  },
  "objects": [
    {
      "label": "person",
      "confidence": 0.91
    }
  ],
  "events": [
    {
      "event_type": "person_detected",
      "description": "Fixture event for dashboard index tests."
    }
  ],
  "risk_score": 0.82,
  "alert_candidates": [
    {
      "type": "person_detected",
      "event_type": "person_detected",
      "severity": "high",
      "title": "Fixture person detected",
      "description": "Fixture alert candidate generated by test data.",
      "risk_score": 0.82,
      "recommended_action": "Review the frame."
    }
  ],
  "raw_response_path": null,
  "status": "mock",
  "mock": true,
  "error": null
}
]=])

set(DRAKON_INDEX_LINE "{\"camera_id\":\"cam_test_01\",\"error\":null,\"frame_id\":\"frame_fixture_alert_01\",\"inference_id\":\"inf_fixture_alert_01\",\"mock\":true,\"model\":\"mock-frame-analyzer-v1\",\"model_provider\":\"mock\",\"record_type\":\"inference\",\"result_path\":\"inference/cam_test_01/2026/05/21/23/inf_fixture_alert_01.json\",\"risk_score\":0.82,\"schema_version\":\"drakon.inference.v1\",\"status\":\"mock\",\"timestamp\":\"2026-05-21T23:00:00.000Z\"}\n")

if(EXISTS "${DRAKON_INFERENCE_INDEX}")
  file(READ "${DRAKON_INFERENCE_INDEX}" DRAKON_INFERENCE_INDEX_CONTENT)
else()
  set(DRAKON_INFERENCE_INDEX_CONTENT "")
endif()

string(FIND "${DRAKON_INFERENCE_INDEX_CONTENT}" "\"result_path\":\"inference/cam_test_01/2026/05/21/23/inf_fixture_alert_01.json\"" DRAKON_FIXTURE_OFFSET)
if(DRAKON_FIXTURE_OFFSET EQUAL -1)
  file(APPEND "${DRAKON_INFERENCE_INDEX}" "${DRAKON_INDEX_LINE}")
endif()
