ALTER TABLE public.cameras
  ADD COLUMN IF NOT EXISTS state_code text;

ALTER TABLE public.cameras
  ADD COLUMN IF NOT EXISTS country_code text;

CREATE TABLE IF NOT EXISTS public.drakon_find_targets (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  entity_type text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  traits_json text NOT NULL DEFAULT '[]',
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.drakon_find_target_images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_id integer NOT NULL REFERENCES public.drakon_find_targets(id) ON DELETE CASCADE,
  storage_key text NOT NULL,
  image_url text NOT NULL,
  content_type text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.drakon_find_searches (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  target_id integer NOT NULL REFERENCES public.drakon_find_targets(id),
  status text NOT NULL DEFAULT 'queued',
  country_code text NOT NULL DEFAULT 'BR',
  selected_states_json text NOT NULL DEFAULT '[]',
  scope_snapshot_json text NOT NULL DEFAULT '{}',
  eligible_camera_count integer NOT NULL DEFAULT 0,
  eligible_owner_count integer NOT NULL DEFAULT 0,
  attempt_count integer NOT NULL DEFAULT 1,
  dispatched_command_count integer NOT NULL DEFAULT 0,
  completed_camera_count integer NOT NULL DEFAULT 0,
  matched_camera_count integer NOT NULL DEFAULT 0,
  hit_count integer NOT NULL DEFAULT 0,
  last_event_at text,
  last_dispatch_at text,
  last_error text,
  started_at text,
  completed_at text,
  cancelled_at text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.drakon_find_search_cameras (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_id integer NOT NULL REFERENCES public.drakon_find_searches(id) ON DELETE CASCADE,
  camera_id integer NOT NULL,
  camera_owner_user_id text NOT NULL,
  camera_name text NOT NULL,
  city text,
  state_code text,
  country_code text,
  is_public_access integer NOT NULL DEFAULT 1,
  assigned_client_id text,
  assigned_exe_id text,
  dispatch_status text NOT NULL DEFAULT 'queued',
  dispatch_command_id integer,
  last_event_type text,
  last_event_at text,
  last_error text,
  started_at text,
  completed_at text,
  match_count integer NOT NULL DEFAULT 0,
  attempt_count integer NOT NULL DEFAULT 0,
  created_at text NOT NULL,
  updated_at text NOT NULL,
  UNIQUE (search_id, camera_id)
);

CREATE TABLE IF NOT EXISTS public.drakon_find_hits (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  search_id integer NOT NULL REFERENCES public.drakon_find_searches(id) ON DELETE CASCADE,
  target_id integer NOT NULL REFERENCES public.drakon_find_targets(id) ON DELETE CASCADE,
  operator_user_id text NOT NULL,
  camera_id integer NOT NULL,
  camera_owner_user_id text NOT NULL,
  client_id text,
  exe_id text,
  attempt_count integer NOT NULL DEFAULT 1,
  summary text NOT NULL DEFAULT '',
  confidence double precision NOT NULL DEFAULT 0,
  image_key text,
  image_url text,
  details_json text NOT NULL DEFAULT '{}',
  matched_at text NOT NULL,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.drakon_find_audit_logs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id text NOT NULL,
  action_type text NOT NULL,
  target_id integer,
  search_id integer,
  message text NOT NULL,
  metadata_json text NOT NULL DEFAULT '{}',
  created_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_cameras_public_scope
  ON public.cameras(allowpublicaccess, country_code, state_code);

CREATE INDEX IF NOT EXISTS idx_drakon_find_targets_user_updated
  ON public.drakon_find_targets(user_id, updated_at);

CREATE INDEX IF NOT EXISTS idx_drakon_find_target_images_target_created
  ON public.drakon_find_target_images(target_id, created_at);

CREATE INDEX IF NOT EXISTS idx_drakon_find_searches_user_status_created
  ON public.drakon_find_searches(user_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_drakon_find_search_cameras_search_id
  ON public.drakon_find_search_cameras(search_id);

CREATE INDEX IF NOT EXISTS idx_drakon_find_search_cameras_client_status
  ON public.drakon_find_search_cameras(search_id, assigned_client_id, dispatch_status);

CREATE INDEX IF NOT EXISTS idx_drakon_find_hits_search_matched
  ON public.drakon_find_hits(search_id, matched_at);

CREATE INDEX IF NOT EXISTS idx_drakon_find_hits_operator_created
  ON public.drakon_find_hits(operator_user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_drakon_find_audit_logs_actor_created
  ON public.drakon_find_audit_logs(actor_user_id, created_at);

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 1;

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS dispatched_command_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS completed_camera_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS matched_camera_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS hit_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS last_event_at text;

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS last_dispatch_at text;

ALTER TABLE public.drakon_find_searches
  ADD COLUMN IF NOT EXISTS last_error text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS assigned_client_id text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS assigned_exe_id text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS dispatch_status text NOT NULL DEFAULT 'queued';

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS dispatch_command_id integer;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS last_event_type text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS last_event_at text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS last_error text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS started_at text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS completed_at text;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS match_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.drakon_find_search_cameras
  ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 0;

ALTER TABLE public.commands
  ADD COLUMN IF NOT EXISTS target_client_id text;

ALTER TABLE public.commands
  ADD COLUMN IF NOT EXISTS target_exe_id text;
