import type { SemanticCapability, SemanticIntentFamily } from "./schema";

const CAPABILITY_REGISTRY: SemanticCapability[] = [
  {
    skill: "read_state",
    label: "Read operational state",
    intent_families: ["read_operational"],
    step_kinds: ["read_operational"],
    planner_mode: "operational_query",
    operations: ["lookup", "aggregate", "compare", "correlate", "explain", "investigate"],
    targets: ["identity", "run", "job", "step", "agent", "camera", "alert", "state"],
    supports_multi_step: true,
    supports_documents: false,
  },
  {
    skill: "generate_report",
    label: "Generate report",
    intent_families: ["report"],
    step_kinds: ["report"],
    planner_mode: "operational_query",
    operations: ["document", "summary", "comparison", "investigation"],
    targets: ["identity", "run", "job", "step", "agent", "camera", "alert", "state"],
    supports_multi_step: true,
    supports_documents: true,
  },
  {
    skill: "control_camera",
    label: "Control camera",
    intent_families: ["run_action"],
    step_kinds: ["run_action"],
    planner_mode: "mutation_grounding",
    operations: ["start", "stop"],
    targets: ["camera"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "control_job",
    label: "Control job",
    intent_families: ["run_action"],
    step_kinds: ["run_action"],
    planner_mode: "mutation_grounding",
    operations: ["start", "stop"],
    targets: ["job"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "create_camera",
    label: "Create camera",
    intent_families: ["create_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["create"],
    targets: ["camera"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "create_cameras_batch",
    label: "Create cameras in batch",
    intent_families: ["create_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["create_batch"],
    targets: ["camera"],
    supports_multi_step: true,
    supports_documents: false,
  },
  {
    skill: "edit_camera",
    label: "Edit camera",
    intent_families: ["edit_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["update"],
    targets: ["camera"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "edit_cameras_batch",
    label: "Edit cameras in batch",
    intent_families: ["edit_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["update_batch"],
    targets: ["camera"],
    supports_multi_step: true,
    supports_documents: false,
  },
  {
    skill: "create_job",
    label: "Create job",
    intent_families: ["create_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["create"],
    targets: ["job"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "edit_job",
    label: "Edit job",
    intent_families: ["edit_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["update"],
    targets: ["job"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "create_camera_agent",
    label: "Create camera agent",
    intent_families: ["create_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["create"],
    targets: ["camera_agent"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "edit_camera_agent",
    label: "Edit camera agent",
    intent_families: ["edit_config"],
    step_kinds: ["mutation"],
    planner_mode: "mutation_grounding",
    operations: ["update"],
    targets: ["camera_agent"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "video_search",
    label: "Search media",
    intent_families: ["search_media"],
    step_kinds: ["search_media"],
    planner_mode: "none",
    operations: ["search", "inspect"],
    targets: ["video", "frame", "media"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "explain_app",
    label: "Explain app",
    intent_families: ["answer"],
    step_kinds: ["answer"],
    planner_mode: "none",
    operations: ["explain"],
    targets: ["app"],
    supports_multi_step: false,
    supports_documents: false,
  },
  {
    skill: "scan_network",
    label: "Scan network",
    intent_families: ["run_action"],
    step_kinds: ["run_action"],
    planner_mode: "none",
    operations: ["scan"],
    targets: ["network"],
    supports_multi_step: false,
    supports_documents: false,
  },
];

export function listSkillCapabilities(): SemanticCapability[] {
  return CAPABILITY_REGISTRY.map((entry) => ({
    ...entry,
    intent_families: [...entry.intent_families],
    step_kinds: [...entry.step_kinds],
    operations: [...entry.operations],
    targets: [...entry.targets],
  }));
}

export function getSkillCapability(skill: string): SemanticCapability | null {
  const capability = CAPABILITY_REGISTRY.find((entry) => entry.skill === skill);
  return capability
    ? {
        ...capability,
        intent_families: [...capability.intent_families],
        step_kinds: [...capability.step_kinds],
        operations: [...capability.operations],
        targets: [...capability.targets],
      }
    : null;
}

export function listCapabilitiesForIntentFamily(intentFamily: SemanticIntentFamily): SemanticCapability[] {
  return CAPABILITY_REGISTRY.filter((entry) => entry.intent_families.includes(intentFamily)).map((entry) => ({
    ...entry,
    intent_families: [...entry.intent_families],
    step_kinds: [...entry.step_kinds],
    operations: [...entry.operations],
    targets: [...entry.targets],
  }));
}
