import { Pool } from "pg";

type BindValue = string | number | boolean | null | undefined | Date | Buffer | Uint8Array;

type QueryMeta = {
  changes?: number;
  last_row_id?: number | null;
};

export type D1Result<T = any> = {
  results?: T[];
  meta?: QueryMeta;
};

const idCache = new Map<string, boolean>();

const COLUMN_CASE_MAP: Record<string, string> = {
  inputtokensm: "InputTokensM",
  outputtokensm: "OutputTokensM",
  inputtokensusedm: "InputTokensUsedM",
  outputtokensusedm: "OutputTokensUsedM",
};

function normalizeValue(value: BindValue) {
  if (value === undefined) return null;
  if (value instanceof Date) return value.toISOString();
  return value;
}

function normalizeRow(row: any) {
  if (!row || typeof row !== "object") return row;
  for (const [from, to] of Object.entries(COLUMN_CASE_MAP)) {
    if (row[from] !== undefined && row[to] === undefined) {
      row[to] = row[from];
    }
  }
  return row;
}

function translateDatetime(sql: string) {
  const convert = (_: string, amountRaw: string, unit: string) => {
    const amount = parseInt(amountRaw, 10);
    const sign = amount >= 0 ? "+" : "-";
    const abs = Math.abs(amount);
    return `CURRENT_TIMESTAMP ${sign} INTERVAL '${abs} ${unit}'`;
  };

  let out = sql;
  out = out.replace(
    /datetime\('now'\s*,\s*'([+-]?\d+)\s*(day|month|hour|minute|second)s?'\)/gi,
    convert
  );
  out = out.replace(
    /datetime\(CURRENT_TIMESTAMP\s*,\s*'([+-]?\d+)\s*(day|month|hour|minute|second)s?'\)/gi,
    convert
  );
  return out;
}

function translateGroupConcat(sql: string) {
  return sql.replace(/GROUP_CONCAT\(\s*([^)]+?)\s*\)/gi, (_match, expr) => {
    const trimmed = String(expr).trim();
    return `STRING_AGG(${trimmed}, ',')`;
  });
}

function translateAutoincrement(sql: string) {
  return sql.replace(
    /\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi,
    "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
  );
}

function replaceParams(sql: string) {
  let out = "";
  let index = 0;
  let inSingle = false;
  let inDouble = false;

  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    if (ch === "'" && !inDouble) {
      inSingle = !inSingle;
      out += ch;
      continue;
    }
    if (ch === '"' && !inSingle) {
      inDouble = !inDouble;
      out += ch;
      continue;
    }
    if (ch === "?" && !inSingle && !inDouble) {
      index += 1;
      out += `$${index}`;
      continue;
    }
    out += ch;
  }

  return out;
}

function translateSql(sql: string) {
  return replaceParams(translateAutoincrement(translateGroupConcat(translateDatetime(sql))));
}

function hasReturning(sql: string) {
  return /\breturning\b/i.test(sql);
}

function isInsert(sql: string) {
  return /^\s*insert\b/i.test(sql);
}

function extractTable(sql: string): string | null {
  const match = /insert\s+into\s+([a-zA-Z0-9_."']+)/i.exec(sql);
  if (!match) return null;
  let table = match[1];
  table = table.replace(/["']/g, "");
  if (table.includes(".")) {
    table = table.split(".").pop() || table;
  }
  return table.toLowerCase();
}

async function tableHasId(pool: Pool, table: string): Promise<boolean> {
  if (idCache.has(table)) {
    return idCache.get(table)!;
  }

  const result = await pool.query(
    `SELECT 1
     FROM information_schema.columns
     WHERE table_schema = 'public'
       AND table_name = $1
       AND column_name = 'id'
     LIMIT 1`,
    [table]
  );

  const hasId = result.rowCount > 0;
  idCache.set(table, hasId);
  return hasId;
}

class PgD1Statement {
  private pool: Pool;
  private sql: string;
  private params: BindValue[];

  constructor(pool: Pool, sql: string, params: BindValue[] = []) {
    this.pool = pool;
    this.sql = sql;
    this.params = params;
  }

  bind(...params: BindValue[]) {
    return new PgD1Statement(this.pool, this.sql, params);
  }

  async all<T = any>(): Promise<D1Result<T>> {
    const text = translateSql(this.sql);
    const values = this.params.map(normalizeValue);
    const result = await this.pool.query(text, values);
    const rows = result.rows.map((row) => normalizeRow(row));
    return { results: rows as T[] };
  }

  async first<T = any>(): Promise<T | null> {
    const { results } = await this.all<T>();
    if (!results || results.length === 0) return null;
    return results[0] as T;
  }

  async run(): Promise<D1Result> {
    let text = translateSql(this.sql);
    const values = this.params.map(normalizeValue);
    let expectsId = false;

    if (isInsert(text) && !hasReturning(text)) {
      const table = extractTable(text);
      if (table && await tableHasId(this.pool, table)) {
        text = `${text} RETURNING id`;
        expectsId = true;
      }
    } else if (hasReturning(text)) {
      expectsId = true;
    }

    const result = await this.pool.query(text, values);
    const lastRowId = expectsId && result.rows && result.rows[0] ? result.rows[0].id : null;

    return {
      meta: {
        changes: result.rowCount ?? 0,
        last_row_id: lastRowId,
      },
    };
  }
}

export class PgD1Database {
  private pool: Pool;

  constructor(pool: Pool) {
    this.pool = pool;
  }

  prepare(sql: string) {
    return new PgD1Statement(this.pool, sql);
  }
}
